#
# Crea il libro con il contenuto di solo questo capitolo.
#
#

CHAPTERS= 	kernel/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..
.include "../Makefile"
