#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/euro/Makefile,v 1.1 2002/09/22 10:47:22 blackend Exp $
#
# Articolo: Il simbolo dell'Euro su FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
