#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/filtering-bridges/Makefile,v 1.2 2002/09/22 10:45:12 blackend Exp $
#
# Articolo: Filtering Bridges

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
