#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/multi-os/Makefile,v 1.1 2002/09/22 10:47:32 blackend Exp $
#
# Articolo: Installazione e Utilizzo di FreeBSD con altri Sistemi Operativi 

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
