#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/explaining-bsd/Makefile,v 1.1 2002/09/22 10:47:26 blackend Exp $
#
# Articolo: Panoramica su BSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
