# $FreeBSD: doc/it_IT.ISO8859-15/articles/Makefile,v 1.4 2003/03/19 19:05:25 trhodes Exp $

SUBDIR =
SUBDIR+= committers-guide
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= vm-design

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
