#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/committers-guide/Makefile,v 1.3 2004/01/26 18:20:03 ale Exp $
#
# Articolo: Guida del Committer

MAINTAINER=ale@FreeBSD.org

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
