#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/vm-design/Makefile,v 1.2 2003/04/11 09:21:15 blackend Exp $
#
# Articolo: Elementi di progettazione del sistema di VM di FreeBSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

SRCS=		article.sgml
IMAGES_EN =	fig1.eps
IMAGES_EN+=	fig2.eps
IMAGES_EN+=	fig3.eps
IMAGES_EN+=	fig4.eps

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=


DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
