#
# $FreeBSD: doc/it_IT.ISO8859-15/articles/new-users/Makefile,v 1.2 2002/09/22 10:44:59 blackend Exp $
#
# Articolo: Per chi e' alle Prime Armi sia con FreeBSD che con Unix
 
DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
